image:
  file: .gitpod.Dockerfile

# 起動時に実行するコマンド
tasks:
  - init: npm install -g npm
  - command : npm install --no-optional
  - command: npm install -g npm-check-updates

# 起動時に開くポート
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - DigitalBrainstem.javascript-ejs-support@1.1.3:xLR8sFkUIbrFhSeHqB85XA==
    - formulahendry.auto-rename-tag@0.1.1:lKCmLIZAiCM0M8AjDnwCLQ==
    - syler.sass-indented@1.7.2:f1BCSRnijorqtRq9iuA2bQ==
    - Zignd.html-css-class-completion@1.19.0:b3YWQQIEP1z3u93nyLX0UA==
    - streetsidesoftware.code-spell-checker@1.7.20:cVP84QuR82xkSPogpSLgJA==
    - xabikos.JavaScriptSnippets@1.7.2:XXmiw8r7K3Guifex/E73aQ==
    - christian-kohler.path-intellisense@1.4.2:QnOrf5fk6KiVaQs4cNEP+w==
    - QassimFarid.ejs-language-support@0.0.1:w4TbdGAviNNiyP8nOqfKrg==
    - abusaidm.html-snippets@0.2.1:7b7Vkkp6Lem9WOqKCYMq2w==
    - 1natsu.insert-br-tag@1.0.0:H+UnL37I41pzuycBeqp4Sg==